// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXoJ0LR8X3ZX-I3ScXzHD5MakaA3hKjxI',
    appId: '1:909905095634:android:2eb7aa0ac658115fd5360b',
    messagingSenderId: '909905095634',
    projectId: 'count-on-it-savar',
    storageBucket: 'count-on-it-savar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Rb7cf9aPPon4JT0eCbRw9HK_CIpDifs',
    appId: '1:909905095634:ios:2433e411e9decf3ed5360b',
    messagingSenderId: '909905095634',
    projectId: 'count-on-it-savar',
    storageBucket: 'count-on-it-savar.appspot.com',
    iosClientId: '909905095634-29lve14ev6eq2ujqd1nul2unhs91hknn.apps.googleusercontent.com',
    iosBundleId: 'com.example.countOnIt',
  );
}
